name: TrackRefinerEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - numpy==1.26.4
  - scipy
  - pandas>= 2.2.2
  - scikit-learn
  - matplotlib
  - opencv-python
  - setuptools
  - scikit-image
  - psutil
  - seaborn
  - PyQt5
